[package]

name = "gaussian"
version = "0.0.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[dependencies.utils]
git = "https://github.com/mitchmindtree/utils-rs"

[dependencies]
rand = "0.1.2"
